name: "My Second Jekyll Template"
description: "my second description"

source:.
destination:_site
url: "http://ayabas.github.io/MysecondJekyllSite/"
baseurl: "/MysecondJekyllSite"
paginate: 10

markdown: rdiscount
permalink: pretty
pygments: true
